### ISSUE TITLE
shellies_discovery not working after python 3.9 upgrade.

### ISSUE THREAD

**Issue by raderarn** [bieniu/ha-shellies-discovery#103]
**Describe the bug**
After upgrade my debian bullseye to python 3.9 shellies_discovery broke down.

**Expected behavior**

**Versions:**
 - Home Assistant: 0.118.5
 - Shellies Discovery: 0.35.3
 - Shelly device firmware: 20201124-091217/v1.9.0@57ac4ad8

**Shellies Discovery automation:**
```yaml
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1"
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
```

**Debug log:**
```
2020-12-09 17:20:20 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running automation actions
2020-12-09 17:20:20 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service
2020-12-09 17:20:20 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Error executing script. Unexpected error for call_service at pos 1: Unknown slice type: <ast.Constant object at 0x7f7aa8aa9820>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await self._async_run_long_action(service_task)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 422, in _async_run_long_action
    long_task.result()
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/core.py", line 1490, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/python_script/__init__.py", line 108, in python_script_service_handler
    execute_script(hass, call.service, call.data)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/python_script/__init__.py", line 140, in execute_script
    execute(hass, filename, source, data)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/python_script/__init__.py", line 147, in execute
    compiled = compile_restricted_exec(source, filename=filename)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/compile.py", line 90, in compile_restricted_exec
    return _compile_restricted_mode(
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/compile.py", line 68, in _compile_restricted_mode
    policy_instance.visit(c_ast)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 1437, in visit_Module
    node = self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 1310, in visit_FunctionDef
    node = self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 1394, in visit_Return
    return self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 873, in visit_Call
    node = self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 966, in visit_Subscript
    args=[node.value, self.transform_slice(node.slice)],
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 390, in transform_slice
    raise NotImplementedError("Unknown slice type: {0}".format(slice_))
NotImplementedError: Unknown slice type: <ast.Constant object at 0x7f7aa8aa9820>
2020-12-09 17:20:20 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery] While executing automation automation.shellies_discovery
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/automation/__init__.py", line 433, in async_trigger
    await self.action_script.async_run(
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 710, in async_run
    await super().async_run()
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await self._async_run_long_action(service_task)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/helpers/script.py", line 422, in _async_run_long_action
    long_task.result()
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/core.py", line 1490, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/python_script/__init__.py", line 108, in python_script_service_handler
    execute_script(hass, call.service, call.data)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/python_script/__init__.py", line 140, in execute_script
    execute(hass, filename, source, data)
  File "/usr/local/lib/python3.9/dist-packages/homeassistant/components/python_script/__init__.py", line 147, in execute
    compiled = compile_restricted_exec(source, filename=filename)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/compile.py", line 90, in compile_restricted_exec
    return _compile_restricted_mode(
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/compile.py", line 68, in _compile_restricted_mode
    policy_instance.visit(c_ast)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 1437, in visit_Module
    node = self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 1310, in visit_FunctionDef
    node = self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 1394, in visit_Return
    return self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 873, in visit_Call
    node = self.node_contents_visit(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 535, in node_contents_visit
    return super(RestrictingNodeTransformer, self).generic_visit(node)
  File "/usr/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 966, in visit_Subscript
    args=[node.value, self.transform_slice(node.slice)],
  File "/root/.homeassistant/deps/lib/python3.9/site-packages/RestrictedPython/transformer.py", line 390, in transform_slice
    raise NotImplementedError("Unknown slice type: {0}".format(slice_))
NotImplementedError: Unknown slice type: <ast.Constant object at 0x7f7aa8aa9820>
```

**Comment by bieniu** [comment]
This is not `Shellies Discovery` issue. If you use a simple script:
```python
my_list = ["one", "two"]
one = my_list[0]
``` 
you'll get the same error.

**Comment by bieniu** [comment]
https://github.com/home-assistant/core/issues/44086

**Comment by raderarn** [comment]
> This is not `Shellies Discovery` issue. If you use a simple script:
> 
> ```python
> my_list = ["one", "two"]
> one = my_list[0]
> ```
> 
> you'll get the same error.

@bieniu, did you actually manage to recreate the problem? I have two Debian installations, both bullseye with Python 3.9.1rc1. One is ok but one is not. I can run this simple script successfully on one of them. It seems like there is some dependency issue.

**Comment by bieniu** [comment]
> did you actually manage to recreate the problem?

Yes

**Comment by mikeage** [comment]
FYI, this was now fixed in home assistant core (upgraded restrictedpython to 5.1), but I suspect it won't be in 2020.12.1 and will need to wait for 2021.01.0.

**Comment by bieniu** [comment]
Yes, we have to wait to 2021.1.0.
