### ISSUE TITLE
python script error after after update from 0.39.4 to 0.39.5

### ISSUE THREAD

**Issue by Kaibob2** [bieniu/ha-shellies-discovery#130]
**Describe the bug**

There  appears a log error after updating from 0.39.4 to 0.39.5 every time the script executes.
As far as I can see everything is working anyway.

**Expected behavior**

  No log error.

**Versions:**
 - Home Assistant:  2021.6.0
 - Shellies Discovery: 0.39.5
 - Shelly device firmware:  20210429-100340/v1.10.4-g3f94cd7

**Shellies Discovery automation:**

```
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'

```

**Debug log:**

```
 2021-06-04 07:31:26 ERROR (SyncWorker_14) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 221, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 3361, in <module>
  File "/usr/local/lib/python3.8/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
```

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/commit/5e1e4110b14c37fd9725417ada5bfa04ff38b60a

Thanks!
