### ISSUE TITLE
Update firmware while on latest

### ISSUE THREAD

**Issue by randy993** [bieniu/ha-shellies-discovery#131]
**Describe the bug**
Hi there! I tried to add 'another' Shelly Dimmer 2, after successfully adding multiple other Shelly devices, but somehow this Dimmer 2 did not get detected by home assistant. It looks to come from a firmware issue.

**Expected behavior**
I expected the device to be automatically added in the MQTT integration after setting the right configuration in the Shelly.

**Versions:**
 - Home Assistant: core-2021.6.6
 - Shellies Discovery: 0.39.6
 - Shelly device firmware: 20200629-130515/release-1.7@28744b8b

**Shellies Discovery automation:**
Standard configuration:
```yaml
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
```

**Debug log:**
```txt
Error executing script: Firmware dated 20210318 is required, please update your device shellydimmer2-483FDA91970B
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 221, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 555, in <module>
ValueError: Firmware dated 20210318 is required, please update your device shellydimmer2-483FDA91970B
```

**Comment by randy993** [comment]
Ok, the problem is fixed. It indeed was my firmware which was not on the right version. I got confused since the Shelly Dimmer 2 said no update was available. Eventually a manual OTA firmware update fixed the problem. Sorry for the ticket, but it can be closed.
(http://{device-ip}/ota?url=http://archive.shelly-support.eu/v1.9.6-dimmer2/SHDM-2_build.zip)
