### ISSUE TITLE
Shelly Vintage firmware not on v.1.11

### ISSUE THREAD

**Issue by adriaanh** [bieniu/ha-shellies-discovery#136]
**Describe the bug**
Shelly Vintage firmware is currently on v1.10.4, v1.11 is not there yet, but the script requires this firmware. 

**Expected behavior**
Expect that the script differs between where the firmware is present (and needed) or not. As the new features (where firmware 1.11 is needed) are not implemented in the Shelly Vintage light bulbs. 

**Versions:**
- Home Assistant: core-2021.8.1
 - Shellies Discovery: 0.40.1
 - Shelly device firmware:  v.10.4

**Shellies Discovery automation:**
```yaml
id: "shellies_discovery"
alias: "Shellies Discovery"
mode: queued
max: 999
trigger:
  platform: mqtt
  topic: shellies/announce
action:
  service: python_script.shellies_discovery
  data:
    id: "{{ trigger.payload_json.id }}"
    mac: "{{ trigger.payload_json.mac }}"
    fw_ver: "{{ trigger.payload_json.fw_ver }}"
    model: "{{ trigger.payload_json.model }}"
    mode: "{{ trigger.payload_json.mode | default }}"
    qos: 2
```

**Debug log:**
```txt
2021-08-05 09:05:25 ERROR (SyncWorker_1) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware dated 20210720 is required, please update your device ShellyVintage-6F28A6
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 221, in execute
exec(compiled.code, restricted_globals)
File "shellies_discovery.py", line 568, in <module>
ValueError: Firmware dated 20210720 is required, please update your device ShellyVintage-6F28A6
2021-08-05 09:05:26 ERROR (SyncWorker_1) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware dated 20210720 is required, please update your device ShellyVintage-6F570F
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 221, in execute
exec(compiled.code, restricted_globals)
File "shellies_discovery.py", line 568, in <module>
ValueError: Firmware dated 20210720 is required, please update your device ShellyVintage-6F570F
2021-08-05 09:05:26 ERROR (SyncWorker_6) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware dated 20210720 is required, please update your device ShellyVintage-D0F3ED
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 221, in execute
exec(compiled.code, restricted_globals)
File "shellies_discovery.py", line 568, in <module>
ValueError: Firmware dated 20210720 is required, please update your device ShellyVintage-D0F3ED
```

**Comment by bieniu** [comment]
Shellies Discovery is only compatible with the latest Shelly firmware. Ask Shelly about firmware 1.11 for Vintage.

**Comment by adriaanh** [comment]
Thank you for the response. I will use 0.39.X, but that one is not compatible with the new 2021.8 energy dashboard. I will ask Shelly about 1.11, but it might be good to add firmware dependency per device type?

**Comment by bieniu** [comment]
> it might be good to add firmware dependency per device type

Shellies Discovery is not an integration, it's a Restricted Python script. Restricted Python is very limited, so it's almost impossible (or possible, but it requires a lot of work) to support different firmware versions.

**Comment by olympia** [comment]
Same issue for Shelly RGBW2, what is also only at v1.10.4.

**Comment by bieniu** [comment]
Yo can use `release candidate` firmware http://repo.shelly.cloud/firmware/rc/

**Comment by olympia** [comment]
@bieniu thanks, it works like a charm. I hope it will still detect the new stable firmware when it gets released (now that it has been updated to an rc manually).

Thank again!

**Comment by bieniu** [comment]
> I hope it will still detect the new stable firmware when it gets released.

Yes, it will.

**Comment by olympia** [comment]
Actually the RGBW2 works perfectly, by my Vintage seems to be discovered only as an on/off light.
Brightness cannot be set (and also cannot be turned on by setting the brightness to 100%) and it can only be turned on/off with the light switch.

Could that be an issue with the rc firmware or the discovery script needs some fine tuning, or is it just me? :)

**Comment by bieniu** [comment]
> Could that be an issue with the rc firmware or the discovery script needs some fine tuning, or is it just me?

I don't know. Please open a new issue (and fill up an issue form).
