### ISSUE TITLE
0.42.0 Shelly Button is not discoverable

### ISSUE THREAD

**Issue by KaiDroste** [bieniu/ha-shellies-discovery#175]
**Describe the bug**
With the last update I am not able to discover my Shelly button 1. After going back to 0.41.1 everything works like expected. 

**Expected behavior**
The devices should be auto discovered 

**Versions:**
 - Home Assistant: core-2021.12.0
 - Shellies Discovery: 0.42.0
 - Shelly device firmware: 20211109-125924/v1.11.7-g682a0db

**Shellies Discovery automation:**

```yaml

```

**Debug log:**

```txt

2021-12-12 11:59:15 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running automation actions
2021-12-12 11:59:15 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service
2021-12-12 11:59:18 INFO (SyncWorker_4) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shellybutton1-98CDAC2C22D4', 'mac': '98CDAC2C22D4', 'fw_ver': '20211109-125924/v1.11.7-g682a0db', 'model': 'SHBTN-2', 'mode': '', 'host': '192.168.178.59'}
2021-12-12 11:59:18 DEBUG (SyncWorker_4) [homeassistant.components.python_script.shellies_discovery.py] id: shellybutton1-98CDAC2C22D4, mac: 98cdac2c22d4, fw_ver: 20211109-125924/v1.11.7-g682a0db, model: SHBTN-2
2021-12-12 11:59:18 ERROR (SyncWorker_4) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
exec(compiled.code, restricted_globals)
File "shellies_discovery.py", line 3133, in <module>
TypeError: 'NoneType' object is not callable
```

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/commit/a7acea0ddab6eca2b130cb4dfd3491a3de84c64e
