### ISSUE TITLE
Upgrading fail

### ISSUE THREAD

**Issue by palinf** [bieniu/ha-shellies-discovery#177]
**Describe the bug**
I updated to the last version - dec6dfd

A lot of entities disappearing and the logs messages are filled with such message:

Any obvious mistake ?

```
2021-12-12 21:06:58 ERROR (MainThread) [homeassistant.util.logging] Exception in discovery_callback when dispatching 'mqtt_discovery_updated_('sensor', 'et1_living_interd1_E098063D4D59-energy-0')': ({'name': 'et1_living_entree_spot Energy', 'state_topic': 'shellies/et1_living_interd1_E098063D4D59/relay/0/energy', 'unit_of_measurement': 'kWh', 'value_template': '{{(value|float/60/1000)|round(2)}}', 'device_class': 'energy', 'availability_topic': 'shellies/et1_living_interd1_E098063D4D59/online', 'payload_available': 'true', 'payload_not_available': 'false', 'force_update': 'False', 'unique_id': 'et1_living_interd1_E098063D4D59-relay-energy-0', 'qos': 0, 'device': {'connections': [['mac', 'e0:98:06:3d:4d:59']], 'name': 'Shelly 2.5 et1_living_interd1_E098063D4D59', 'model': 'Shelly 2.5', 'sw_version': '20211109-125214/v1.11.7-g682a0db', 'manufacturer': 'Allterco Robotics', 'cu': 'http://None/'}, 'state_class': 'total_increasing', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 449, in discovery_callback
    await self._discovery_update(payload)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 592, in discovery_update
    config = self.config_schema()(discovery_payload)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['device']['cu']

```

**Comment by bieniu** [comment]
![image](https://user-images.githubusercontent.com/478555/145734217-1fac0fe8-da69-4330-9853-157f5d9344b1.png)
