### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by johntdyer** [bieniu/ha-shellies-discovery#2]
I have the following config

```yaml
automation:
  - id: shellies_announce
    alias: 'Shellies Announce'
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: mqtt.publish
      data:
        topic: shellies/command
        payload: announce

  - id: 'shellies_discovery'
    alias: 'Shellies Discovery'
    trigger:
      - platform: mqtt
        topic: shellies/announce
    action:
      service: python_script.shellies_discovery
      data_template:
        id: '{{ trigger.payload_json.id }}'
        mac: '{{ trigger.payload_json.mac }}'
        fw_ver: '{{ trigger.payload_json.fw_ver }}'
        discovery_prefix: 'hass'
        temp_unit: 'F'
        qos: 2
        shelly1-001122-relay-0: 'light'
        shellyswitch-9900AA-relay-0: 'light'
        shellyswitch-9900AA-relay-1: 'fan'
        shellyswitch25-334411-relay-1: 'light'
        shellyswitch-334455: 'cover'
        shellyrgbw2-AABB22: 'white'
        shellyrgbw2-CC2211: 'rgbw'
        shellyht-2200AA: 'ac_power'
```

and when I run the discovery script

```root@ubuntu:~# hass-cli -x service  call python_script.shellies_discovery
[]

```

 I get the following error

```
2019-09-12 07:59:13 INFO (SyncWorker_5) [homeassistant.components.python_script] Executing shellies_discovery.py: {}
2019-09-12 07:59:13 ERROR (SyncWorker_5) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 197, in execute
    exec(compiled.code, restricted_globals, local)
  File "shellies_discovery.py", line 219, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bieniu** [comment]
This is an example of configuration. Yo have to use yours devices IDs.
This is not a whole traceback.

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.12.2
