### ISSUE TITLE
Spelling issue in error message "shallies_discovery"

### ISSUE THREAD

**Issue by jshank** [bieniu/ha-shellies-discovery#223]
**Describe the bug**

There is a minor spelling issue in the host value Non error on line 913, `shallies_discovery`

```python
if not host:
    raise ValueError(
        "host value None is not valid, update shallies_discovery automation"
    )
```

**Expected behavior**

Error message comes from shellies_discovery

**Versions:**
 - Home Assistant: 2021.12.8
 - Shellies Discovery: 0.43.2
 - Shelly device firmware: N/A

**Shellies Discovery automation:**

```yaml

```
N/A

**Debug log:**

```txt
2022-01-05 10:12:35 ERROR (SyncWorker_3) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: host value None is not valid, update shallies_discovery automation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 895, in <module>
ValueError: host value None is not valid, update shallies_discovery automation
2022-01-05 10:12:55 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states("sensor.dryer_current")|float > 2 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1

```

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/pull/227
