### ISSUE TITLE
host value None is not valid, update shellies_discovery automation

### ISSUE THREAD

**Issue by Veldkornet** [bieniu/ha-shellies-discovery#239]
**Describe the bug**

This error keeps spamming my logs. Unsure which device it may be... Door Window Sensor maybe?

**Expected behavior**

**Versions:**
 - Home Assistant: 2021.12.9
 - Shellies Discovery: 0.43.4
 - Shelly device firmware: 

**Shellies Discovery automation:**

```yaml

```

**Debug log:**

```txt
2022-01-11 20:05:12 ERROR (SyncWorker_7) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: host value None is not valid, update shellies_discovery automation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1094, in <module>
ValueError: host value None is not valid, update shellies_discovery automation
```

**Comment by MikevanDongen** [comment]
This issue probably has to do with the warning in this changelog: https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.41.0

**Comment by bieniu** [comment]
host value None is not valid, **update shellies_discovery automation**
