### ISSUE TITLE
Discovery Script fails to be executed

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#247]
**Describe the bug**
The script crashes and doesn't run, no devices are discovered

**Expected behavior**
The script should work

**Versions:**
 - Home Assistant:  2021.12.10
 - Shellies Discovery:  0.43.7
 - Shelly device firmware:  1.11.7
 - 
**Shellies Discovery automation:**

```yaml
alias: Shellies Discovery
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      qos: 2
      livingroom-motion:
        powered: battery
      kitchen-motion:
        powered: battery
      button01:
        powered: battery
      button02-white:
        powered: battery
mode: queued
max: 999

```

**Debug log:**

```txt
2022-01-20 08:46:04 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running automation actions
2022-01-20 08:46:04 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service
2022-01-20 08:46:04 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Erroneous JSON:
2022-01-20 08:46:05 INFO (SyncWorker_2) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'bedroom-window-blinds', 'mac': 'D8BFC01A67FC', 'fw_ver': '20211109-125214/v1.11.7-g682a0db', 'model': 'SHSW-25', 'mode': 'roller', 'qos': 2, 'livingroom-motion': {'powered': 'battery'}, 'kitchen-motion': {'powered': 'battery'}, 'button01': {'powered': 'battery'}, 'button02-white': {'powered': 'battery'}}
2022-01-20 08:46:05 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: host value None is not valid, update shellies_discovery automation
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
exec(compiled.code, restricted_globals)
File "shellies_discovery.py", line 1207, in <module>
ValueError: host value None is not valid, update shellies_discovery automation
2022-01-20 08:46:05 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running automation actions
2022-01-20 08:46:05 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service
2022-01-20 08:46:06 INFO (SyncWorker_0) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'wooden-lamp', 'mac': 'E8DB84D6AB5C', 'fw_ver': '20211109-131033/v1.11.7-g682a0db', 'model': 'SHDM-2', 'mode': '', 'qos': 2, 'livingroom-motion': {'powered': 'battery'}, 'kitchen-motion': {'powered': 'battery'}, 'button01': {'powered': 'battery'}, 'button02-white': {'powered': 'battery'}}
```

the traceback happens for every device unsering the announce, another example

```
2022-01-20 08:46:04 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running automation actions
2022-01-20 08:46:04 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service
2022-01-20 08:46:04 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Erroneous JSON:
2022-01-20 08:46:05 INFO (SyncWorker_2) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'bedroom-window-blinds', 'mac': 'D8BFC01A67FC', 'fw_ver': '20211109-125214/v1.11.7-g682a0db', 'model': 'SHSW-25', 'mode': 'roller', 'qos': 2, 'livingroom-motion': {'powered': 'battery'}, 'kitchen-motion': {'powered': 'battery'}, 'button01': {'powered': 'battery'}, 'button02-white': {'powered': 'battery'}}
2022-01-20 08:46:05 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: host value None is not valid, update shellies_discovery automation
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
exec(compiled.code, restricted_globals)
File "shellies_discovery.py", line 1207, in <module>
ValueError: host value None is not valid, update shellies_discovery automation
2022-01-20 08:46:05 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running automation actions
2022-01-20 08:46:05 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service
2022-01-20 08:46:06 INFO (SyncWorker_0) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'wooden-lamp', 'mac': 'E8DB84D6AB5C', 'fw_ver': '20211109-131033/v1.11.7-g682a0db', 'model': 'SHDM-2', 'mode': '', 'qos': 2, 'livingroom-motion': {'powered': 'battery'}, 'kitchen-motion': {'powered': 'battery'}, 'button01': {'powered': 'battery'}, 'button02-white': {'powered': 'battery'}}
```

**Comment by bieniu** [comment]
Please read this error once again `host value None is not valid, update shellies_discovery automation`.

**Comment by anubisg1** [comment]
Hello,

i am sorry i do not understand. 

was the shelly discovery script changed ? when was this breaking change introduced?
