### ISSUE TITLE
Firmware dated 20210720 is required, update your device shellyplug-s

### ISSUE THREAD

**Issue by ForsetiJan** [bieniu/ha-shellies-discovery#248]
**Describe the bug**
Discovery fails due to a mismatch in version. However the version on the plug-s is actually newer.  

**Expected behavior**
Succesfull discovery

**Versions:**
 - Home Assistant: 2021.12.10
 - Shellies Discovery: 0.43.7
 - Shelly device firmware: 20210115-103659/v1.9.4@e2732e05

**Shellies Discovery automation:**
```yaml
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
```

**Debug log:**
```txt
2022-01-20 16:15:17 INFO (SyncWorker_4) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shellyplug-s', 'mac': 'xxxxxxxxx', 'fw_ver': '20210115-103659/v1.9.4@e2732e05', 'model': 'SHPLG-S', 'mode': '', 'host': 'x.x.x.x'}
2022-01-20 16:15:17 ERROR (SyncWorker_4) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware dated 20210720 is required, update your device shellyplug-s'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1277, in <module>
ValueError: Firmware dated 20210720 is required, update your device shellyplug-s'
```

**Comment by ForsetiJan** [comment]
NVM, I am blind
