### ISSUE TITLE
Shellies discovery not working since 2022.4.0

### ISSUE THREAD

**Issue by vacumet** [bieniu/ha-shellies-discovery#277]
Shellies discovery not working since 2022.4.0

**Versions:**
 - Home Assistant: 2022.4.0
 - Shellies Discovery: 0.44.2
 - Shelly device firmware: Latest (20220209-095044/v1.11.8-g8c7bb8d)

**Shellies Discovery automation:**
alias: Shellies Discovery
mode: queued
max: 999
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      discovery_prefix: homeassistant
      qos: 2
      shelly1-AABB9900:
        relay-0: light
        ext-temperature-0: true
        ext-temperature-1: true
        ext-temperature-2: true
        force_update_sensors: true
      shelly1pm-aabb9911:
        ext-temperature-0: true
        ext-humidity-0: true
        longpush_off_delay: false
        force_update_sensors: true
      shellyswitch-123409FF:
        relay-0: fan
        relay-1: light
      shellyswitch-123409cc:
        relay-1: fan
      shellyswitch25-334455AA:
        mode: roller
        position_template: '{{ ''{% if value | float < 30 %}0{% else %}{{ value }}{% endif %}'' }}'
        set_position_template: >-
          {{ '{%if position | float < 30 %}0{% else %}{{ position }}{% endif %}'
          }}
      shellyplug-s-CCBBCCAA:
        relay-0: light
        force_update_sensors: true
      shellyht-11AA00CCDD:
        force_update_sensors: true
        expire_after: 500
      shellyht-11AA00CCEE:
        powered: battery
      shellyht-11AA00CCFF:
        powered: ac
      shellyrgbw2-AA123FF32:
        mode: white
      shellyrgbw2-AA123FF84:
        mode: rgbw
      shellyem-BB23CC45:
        force_update_sensors: true
      ignored_devices:
        - shelly1-DD0011
        - shellyem-EECC22

**Debug log:**
Logger: homeassistant.components.python_script.shellies_discovery.py
Source: components/python_script/__init__.py:224
Integration: Python Scripts (documentation, issues)
First occurred: 20:36:49 (4 occurrences)
Last logged: 20:36:49

Error executing script: host value None is not valid, update shellies_discovery automation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1598, in <module>
ValueError: host value None is not valid, update shellies_discovery automation

**Comment by vacumet** [comment]
I just did that. Sorry
Will update my automation

**Comment by vacumet** [comment]
I updated it and it runs. New error message about a plug with old firmware.
Logger: homeassistant.components.python_script.shellies_discovery.py
Source: components/python_script/__init__.py:224
Integration: Python Scripts (documentation, issues)
First occurred: 20:50:34 (1 occurrences)
Last logged: 20:50:34

Error executing script: Firmware dated 20220209 is required, update your device shellyplug-F9D530
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1647, in <module>
ValueError: Firmware dated 20220209 is required, update your device shellyplug-F9D530


"Current version: 20210115-103101/v1.9.4@e2732e05
You have latest version on your device!"

Maybe i have to do manual update

**Comment by bieniu** [comment]
It seems there is no newer firmware than 1.9.4 for SHPLG-1. I'll fix this tomorrow.
