### ISSUE TITLE
Errors in log after update to 0.19

### ISSUE THREAD

**Issue by dodg3r** [bieniu/ha-shellies-discovery#44]
Hi.

After update to 0.19 i get this in logs.

`2020-05-15 08:04:56 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'shellies/shellyplug-s-B86AC1/temperature': '30.15'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 34, in wrapper
    _log_message(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 24, in _log_message
    messages = debug_info["entities"][entity_id]["subscriptions"][
KeyError: 'sensor.shelly_plug_s_b86ac1_temperature'

2020-05-15 08:04:58 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'shellies/shellyplug-s-B86AC1/relay/0/energy': '0'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 34, in wrapper
    _log_message(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 24, in _log_message
    messages = debug_info["entities"][entity_id]["subscriptions"][
KeyError: 'sensor.shelly_plug_s_b86ac1_energy_0'

2020-05-15 08:05:04 ERROR (MainThread) [homeassistant.util.logging] Exception in state_message_received when handling msg on 'shellies/shellyplug-s-B86AC1/overtemperature': '0'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 34, in wrapper
    _log_message(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 24, in _log_message
    messages = debug_info["entities"][entity_id]["subscriptions"][
KeyError: 'binary_sensor.shelly_plug_s_b86ac1_overtemperature'

2020-05-15 08:05:13 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'shellies/shellyplug-s-B86AC1/relay/0/power': '0.00'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 34, in wrapper
    _log_message(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 24, in _log_message
    messages = debug_info["entities"][entity_id]["subscriptions"][
KeyError: 'sensor.shelly_plug_s_b86ac1_power_0'

Do you know whats wrong or do I need to enable deubg ?`

**Comment by bieniu** [comment]
These errors are not related to the script. Have you migrated correctly to version 0.19.0 as per the instructions?

**Comment by dodg3r** [comment]
Yes, I followed your migrate description and everything works. Execpt for the errors.
The errors is filling my log file with errors on all my nodes.

If this is not related to your script then you can close this issue. Sorry.
Strange that it happend after the update..

**Comment by bieniu** [comment]
Have you restarted HA after migration?

**Comment by dodg3r** [comment]
I found the problem.
Strange because this has never happened before I updated.

If I change the enitity id i must do a restart or else I get this errors.

**Comment by bieniu** [comment]
Really strange. HA 0.109?

**Comment by dodg3r** [comment]
Yes, 109.6

**Comment by dodg3r** [comment]
Because of the migration I renamed all of my devices and it might be some other ha update causing this. Because it was a long time since I renamed devices...
