### ISSUE TITLE
0.21 NoneType error

### ISSUE THREAD

**Issue by ohadlevy** [bieniu/ha-shellies-discovery#48]
Hi,

The script fails with the following output:
```
2020-05-27 18:00:32 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:34 ERROR (SyncWorker_19) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:34 ERROR (SyncWorker_9) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:35 ERROR (SyncWorker_14) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:35 ERROR (SyncWorker_11) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:39 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:41 ERROR (SyncWorker_19) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
2020-05-27 18:00:41 ERROR (SyncWorker_9) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 535, in <module>
TypeError: 'NoneType' object is not callable
```

no configuration changes

**Comment by bieniu** [comment]
Please post script configuration and debug log.

**Comment by ohadlevy** [comment]
I just realized there was a breaking change in configuration, and I had to change all of the configuration into the new syntax :(

while it works, all of my devices got duplicated, so I guess we can solve this issue, would appreciate any pointers on solving the duplicates as I really hate to redefine all the devices names / areas etc

**Comment by bieniu** [comment]
You can remove devices with old entities.
![Screenshot_20200527-230136](https://user-images.githubusercontent.com/478555/83071908-27a20e00-a06e-11ea-81f6-af50a535555a.jpg)

**Comment by ohadlevy** [comment]
On Thu, 28 May 2020, 0:03 Maciej Bieniek, <notifications@github.com> wrote:

> You can remove devices with old entities.
>

Thanks, I can but I need to reconfigure all the new ones, probably will be
faster than trying to find another solution.. thanks
