### ISSUE TITLE
0.25.5

### ISSUE THREAD

**Issue by ruisilvacarvalho** [bieniu/ha-shellies-discovery#57]
Hi ,

I have 62 shellies, only with shellydw i have a issue, the part of vibration:

Shelly windows/door sensor vibration error log:
```
 return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: invalid template (TemplateSyntaxError: unexpected '%') for dictionary value @ data['value_template']
2020-07-08 15:58:28 ERROR (SyncWorker_18) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1399, in 
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-07-08 15:58:28 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_binary_sensor_mqtt': ({'name': 'Shelly Door/Window 764B7A Vibration', 'state_topic': 'shellies/shellydw-764B7A/announce', 'unique_id': 'shellydw-764b7a-vibration', 'qos': 0, 'device': {'identifiers': ['dc4f22764b7a'], 'name': 'Shelly Door/Window 764B7A', 'model': 'Shelly Door/Window', 'sw_version': '20200625-102424/v1.7.3@2aa0993a', 'manufacturer': 'Allterco Robotics'}, 'value_template': "{{% if value_json.id == '{0}' and value_json.new_fw == true %}}ON{{% else %}}OFF{{% endif %}}", 'expire_after': 43200, 'device_class': 'vibration', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/binary_sensor.py", line 85, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: invalid template (TemplateSyntaxError: unexpected '%') for dictionary value @ data['value_template']
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: invalid template (TemplateSyntaxError: unexpected '%') for dictionary value @ data['value_template']
```
Tks

**Comment by bieniu** [comment]
Fixed via: https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.25.6
