### ISSUE TITLE
HA constantly reported issue

### ISSUE THREAD

**Issue by LorenzoBianconi** [bieniu/ha-shellies-discovery#581]
HA reports the following error running the script:

Logger: homeassistant.components.python_script.shellies_discovery.py
Source: components/python_script/__init__.py:270
integration: Python Scripts (documentation, issues)
First occurred: 12:46:01 PM (30 occurrences)
Last logged: 4:00:05 PM

Error executing script
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 270, in execute
    exec(compiled.code, restricted_globals)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shellies_discovery.py", line 1536, in <module>
ValueError: host value  is not valid, update shellies_discovery automation

**Comment by bieniu** [comment]
Configure the `logger` with this instruction https://github.com/bieniu/ha-shellies-discovery?tab=readme-ov-file#how-to-debug
and attach here the log file.

**Comment by bieniu** [comment]
And please fill in the issue form.

**Comment by LorenzoBianconi** [comment]
> Configure the `logger` with this instruction https://github.com/bieniu/ha-shellies-discovery?tab=readme-ov-file#how-to-debug and attach here the log file.

these are the relevant info I got:

2024-07-11 16:18:55.829 INFO (MainThread) [homeassistant.components.automation.mqtt_shelly_announce] mqtt: shelly announce: Running automation actions
2024-07-11 16:18:55.830 INFO (MainThread) [homeassistant.components.automation.mqtt_shelly_announce] mqtt: shelly announce: Executing step call service
2024-07-11 16:18:55.845 INFO (MainThread) [homeassistant.components.automation.mqtt_shelly_discovery] mqtt: shelly discovery: Running automation actions
2024-07-11 16:18:55.846 INFO (MainThread) [homeassistant.components.automation.mqtt_shelly_discovery] mqtt: shelly discovery: Executing step call service
2024-07-11 16:18:55.851 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'fw_ver' when rendering '{{ trigger.payload_json.fw_ver }}'
2024-07-11 16:18:55.852 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'ip' when rendering '{{ trigger.payload_json.ip }}'
2024-07-11 16:18:56.814 INFO (SyncWorker_2) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shelly1pmg3-34b7dac95ad8', 'mac': '34B7DAC95AD8', 'fw_ver': '', 'model': 'S3SW-001P16EU', 'mode': '', 'host': ''}
2024-07-11 16:18:56.815 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery.py] Error executing script
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 270, in execute
    exec(compiled.code, restricted_globals)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shellies_discovery.py", line 1536, in <module>
ValueError: host value  is not valid, update shellies_discovery automation

**Comment by bieniu** [comment]
This script is for Shelly Gen1 devices and you’re trying to configure Gen3 device. You need to use https://github.com/bieniu/ha-shellies-discovery-gen2

**Comment by bieniu** [comment]
That means your shellies_discovery automation is not up-to-date. You need to update it.

**Comment by LorenzoBianconi** [comment]
> That means your shellies_discovery automation is not up-to-date. You need to update it.

I updated it, but still have the same issue. Below I report my automations:

  alias: "mqtt: shelly discovery"
  description: mqtt shelly v1 discovery automation
  trigger:
    - platform: mqtt
      topic: shellies/announce
  condition: []
  action:
    - service: python_script.shellies_discovery
      data:
        id: "{{ trigger.payload_json.id }}"
        mac: "{{ trigger.payload_json.mac }}"
        fw_ver: "{{ trigger.payload_json.fw_ver }}"
        model: "{{ trigger.payload_json.model | default }}"
        mode: "{{ trigger.payload_json.mode | default }}"
        host: "{{ trigger.payload_json.ip }}"
        ignored_devices:
          - shellyplus1pm-xxxxxxxxxxx
          - shelly1pmg3-xxxxxxxxxxx

Am I missing something?
