### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by meizenga** [bieniu/ha-shellies-discovery#64]
2020-07-28 23:33:59 ERROR (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 265, in <module>
TypeError: 'NoneType' object is not callable

Using HA 0.113.2 (error is the same for 0.113.1)
Getting this error when running the shellies discovery service

**Comment by meizenga** [comment]
My bad... some typo.. Nuke this issue please ;)

**Comment by ghust** [comment]
Where was your typo? I'm having same issue, but I haven't really changed anything... I think :)

**Comment by divemasterjm** [comment]
i have same issue

**Comment by bieniu** [comment]
Don't comment closed issue, please open new one.
