### ISSUE TITLE
Version 0.27.7 indicated that update of FW is required while devices are already on 1.8.0

### ISSUE THREAD

**Issue by henrikpieter** [bieniu/ha-shellies-discovery#74]
I'm running the script but get an error. It indicates that there's a FW upgrade required but my devices already are on 1.8.0. This was the reason for me to move to MQTT.

Try as you can see also with a disabled forced_upgrade_sensor, but no effect.
=============
2020-08-23 15:40:15 ERROR (SyncWorker_19) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware version 1.8.0 is required, please update your device {{ trigger.payload_json.id }}
Traceback (most recent call last):
  File "shellies_discovery.py", line 350, in <module>
  File "/usr/local/lib/python3.8/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 352, in <module>
ValueError: Firmware version 1.8.0 is required, please update your device {{ trigger.payload_json.id }}
2020-08-23 15:40:16 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] shellies_discovery: Running script
2020-08-23 15:40:16 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] shellies_discovery: Executing step call service
2020-08-23 15:40:16 INFO (SyncWorker_12) [homeassistant.components.python_script] Executing shellies_discovery.py: {'fw_ver': '{{ trigger.payload_json.fw_ver }}', 'id': '{{ trigger.payload_json.id }}', 'mac': '{{ trigger.payload_json.mac }}', 'shelly1pm-68C63AFAD367': OrderedDict([('force_update_sensors', False)]), 'shellydimmer-DB3DAC': OrderedDict([('force_update_sensors', False)])}
2020-08-23 15:40:16 ERROR (SyncWorker_12) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware version 1.8.0 is required, please update your device {{ trigger.payload_json.id }}
Traceback (most recent call last):
  File "shellies_discovery.py", line 350, in <module>
  File "/usr/local/lib/python3.8/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 352, in <module>
ValueError: Firmware version 1.8.0 is required, please update your device {{ trigger.payload_json.id }}

=================

**Comment by bieniu** [comment]
Show me your Shelly related automations.

**Comment by henrikpieter** [comment]
- id: '1598175936472'
  alias: shellies_announce
  description: shellies_announce
  trigger:
  - event: start
    platform: homeassistant
  - hours: /1
    platform: time_pattern
  condition: []
  action:
  - data:
      payload: announce
      topic: shellies/command
    service: mqtt.publish
  mode: single
- id: '1598176170090'
  alias: shellies_discovery
  description: shellies_discovery
  trigger:
  - platform: mqtt
    topic: shellies/announce
  condition: []
  action:
  - data:
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
    service: python_script.shellies_discovery
  mode: queued
  max: 99

**Comment by bieniu** [comment]
`data_template` is missing in the `shellies discovery` automation.

**Comment by henrikpieter** [comment]
Thanks Maciej,

This indeed solved the problem.

Owe you a good coffee.

Henrik

Op zo 23 aug. 2020 21:45 schreef Maciej Bieniek <notifications@github.com>:

**Comment by bieniu** [comment]
Thanks!
