### ISSUE TITLE
Shelly4pro Firmware Version

### ISSUE THREAD

**Issue by pjbpaul** [bieniu/ha-shellies-discovery#75]
Hi, firstly let me say thankyou for the excellent work you have done on this script. 
I have Shelly 1's, Shelly 2.5's and shelly rgbw2's that are discovered without problems. But it does say that the scrips supports shelly 4pro's, but the latest firmware for the shelly 4pro is less than 1.8.0, it is 20200716-114943/1.6.5_4Pro@2092f96b so they are not detected. Is it possible for this firmware to be accepted by your script ? I have included the entry from the log below.

Many Thanks Paul.

2020-08-22 16:35:55 INFO (SyncWorker_56) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shellypro4-4', 'mac': 'E415F64D0105', 'fw_ver': '20200716-114943/1.6.5_4Pro@2092f96b'}
2020-08-22 16:35:55 ERROR (SyncWorker_56) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware version 1.8.0 is required, please update your device shellypro4-4
Traceback (most recent call last):

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.27.8
@pjbpaul Please let me know when firmware 1.8.0 will be available for 4Pro.

**Comment by pjbpaul** [comment]
Hi,
I tried the new script and it not working I'm afraid. I had a custom mqtt prefix so I put to default but no use. Here is the log.

Thanks

2020-08-24 19:35:40 INFO (SyncWorker_20) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shelly4pro-4D0105', 'mac': 'E415F64D0105', 'fw_ver': '20200716-114943/1.6.5_4Pro@2092f96b'}
2020-08-24 19:35:40 ERROR (SyncWorker_20) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: Firmware version 1.8.0 is required, please update your device shelly4pro-4D0105
Traceback (most recent call last):
  File "shellies_discovery.py", line 351, in <module>
  File "/usr/local/lib/python3.8/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 353, in <module>
ValueError: Firmware version 1.8.0 is required, please update your device shelly4pro-4D0105

**Comment by bieniu** [comment]
Stupid version naming of Shelly 🤦

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.27.10

**Comment by pjbpaul** [comment]
Hi,
Many Thanks that works well now. There is a couple of errors in the logs but it detected my 4pro great. I will include the log in case you want to have a look at. There was just one other thing, it would be good if you could include the version number of the script in the comment at the top of the script, it would make it easy to see if an update is available.
But many thanks very useful script.
Paul

[home-assistant.log](https://github.com/bieniu/ha-shellies-discovery/files/5125906/home-assistant.log)

**Comment by bieniu** [comment]
Thanks for the drink!
Log errors are related to the Alexa component, not to the script. You can now remove `homeassistant.components.python_script: debug` from your configuration as it is only useful during installation and configuration.
It is most convenient to install the script via HACS then you will receive notifications about the availability of a new version.
