### ISSUE TITLE
NoneType Object is not callable

### ISSUE THREAD

**Issue by ghust** [bieniu/ha-shellies-discovery#78]
Stacktrace:

Log Details (ERROR)
Logger: homeassistant.components.python_script.shellies_discovery.py
Source: components/python_script/__init__.py:205
Integration: Python Scripts (documentation, issues)
First occurred: 9:39:04 AM (1 occurrences)
Last logged: 9:39:04 AM

Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 1401, in <module>
TypeError: 'NoneType' object is not callable

More data:

2020-09-04 09:39:04 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Running script,
2020-09-04 09:39:04 INFO (MainThread) [homeassistant.components.automation.shellies_discovery] Shellies Discovery: Executing step call service,
2020-09-04 09:39:04 INFO (SyncWorker_4) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shellyswitch25-68DE2A', 'mac': '2CF43268DE2A', 'fw_ver': '20200827-065456/v1.8.3@4a8bc427', 'model': 'SHSW-25', 'shelly1_246334_relay_0': 'light', 'shelly1_2c8012_relay_0': 'light', 'shelly1_55dE73_relay_0': 'light', 'shelly1_59dA5c_relay_0': 'light', 'shelly1_E0E863_relay_0': 'light', 'shelly1_E2CDCD_relay_0': 'light', 'shellyswitch25-E619B2-relay-1': 'fan', 'shellyswitch25-E619B2-relay-0': 'light', 'shellyswitch25-E61B55-relay-1': 'fan', 'shellyswitch25-E61B55-relay-0': 'light', 'shellyswitch25-688455-relay-1': 'light', 'shelly1_BA3DAF_relay_0': 'light', 'shelly1_e2d1bc_relay_0': 'light', 'shellyswitch25-68DE2A': 'cover', 'shellydimmer-DB3B75': 'dimmer'},
2020-09-04 09:39:04 DEBUG (SyncWorker_4) [homeassistant.components.python_script.shellies_discovery.py] dev_id: shellyswitch25-68DE2A, mac: 2cf43268de2a, fw_ver: 20200827-065456/v1.8.3@4a8bc427, model_id: SHSW-25,
2020-09-04 09:39:04 ERROR (SyncWorker_4) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute,
    exec(compiled.code, restricted_globals),
  File "shellies_discovery.py", line 1401, in <module>,
TypeError: 'NoneType' object is not callable,

This is for a roller shutter.

Have it for another one (dimmer 1):

2020-09-04 09:42:05 INFO (SyncWorker_32) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shellydimmer-DB3B75', 'mac': '84F3EBDB3B75', 'fw_ver': '20200827-070608/v1.8.3@4a8bc427', 'model': 'SHDM-1', 'shelly1_246334_relay_0': 'light', 'shelly1_2c8012_relay_0': 'light', 'shelly1_55dE73_relay_0': 'light', 'shelly1_59dA5c_relay_0': 'light', 'shelly1_E0E863_relay_0': 'light', 'shelly1_E2CDCD_relay_0': 'light', 'shellyswitch25-E619B2-relay-1': 'fan', 'shellyswitch25-E619B2-relay-0': 'light', 'shellyswitch25-E61B55-relay-1': 'fan', 'shellyswitch25-E61B55-relay-0': 'light', 'shellyswitch25-688455-relay-1': 'light', 'shelly1_BA3DAF_relay_0': 'light', 'shelly1_e2d1bc_relay_0': 'light', 'shellyswitch25-68DE2A': 'cover', 'shellydimmer-DB3B75': 'dimmer'},
2020-09-04 09:42:05 DEBUG (SyncWorker_32) [homeassistant.components.python_script.shellies_discovery.py] dev_id: shellydimmer-DB3B75, mac: 84f3ebdb3b75, fw_ver: 20200827-070608/v1.8.3@4a8bc427, model_id: SHDM-1,
2020-09-04 09:42:05 ERROR (SyncWorker_32) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute,
    exec(compiled.code, restricted_globals),
  File "shellies_discovery.py", line 1687, in <module>,
TypeError: 'NoneType' object is not callable

Any idea? I'm not that good with python, but when I try to log the device_config, it just gives me an empty object

**Comment by bieniu** [comment]
Please format the log correctly and show me your `shellies_discovery` automation.

**Comment by ghust** [comment]
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /6
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      shelly1_246334_relay_0: light
      shelly1_2c8012_relay_0: light
      shelly1_55dE73_relay_0: light
      shelly1_59dA5c_relay_0: light
      shelly1_E0E863_relay_0: light
      shelly1_E2CDCD_relay_0: light
      shellyswitch25-E619B2-relay-1: fan
      shellyswitch25-E619B2-relay-0: light
      shellyswitch25-E61B55-relay-1: fan
      shellyswitch25-E61B55-relay-0: light
      shellyswitch25-688455-relay-1: light
      shelly1_BA3DAF_relay_0: light
      shelly1_e2d1bc_relay_0: light
      shellyswitch25-68DE2A: cover
      shellydimmer-DB3B75: dimmer


How do you want the log formatted?

**Comment by bieniu** [comment]
> How do you want the log formatted?

https://docs.github.com/en/enterprise/2.20/user/github/writing-on-github/basic-writing-and-formatting-syntax

Your configuration is invalid: https://github.com/bieniu/ha-shellies-discovery#custom-configuration-example

**Comment by ghust** [comment]
Oh, I must have updated to a new version, as I'm pretty sure that used to be the syntax?

Thanks for the help, I'll see if this will work

**Comment by bieniu** [comment]
Yes, that's the old syntax.
