### ISSUE TITLE
error when running Shellies Discovery

### ISSUE THREAD

**Issue by volzb** [bieniu/ha-shellies-discovery#86]
Hi, 

this error shows up when I run Shellies Discovery on HA 0.115.6

General
Server Controls
Logs
Info
Shellies Discovery: Error executing script. Unexpected error for call_service at pos 1: Error rendering data template: UndefinedError: 'trigger' is undefined
6:34:04 PM – Automation (ERROR) - message first occurred at 6:33:38 PM and shows up 12 times

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 285, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'trigger' is undefined

The above exception was the direct cause of the following exception:

**Comment by bieniu** [comment]
Please read the documentation.

**Comment by volzb** [comment]
A little more information then read the doc would be helpful as I'm not sure what I have missed?

**Comment by bieniu** [comment]
Last point on the troubleshooting checklist: https://github.com/bieniu/ha-shellies-discovery#troubleshooting-checklist
